name: Download latest COVID-19 status vaccination

on:
  schedule:
    - cron: 0 */6 * * *

jobs:
  downloadStatus:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js version 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    - run: npm run download-today-status
